name: Auto publish

on:
  push:
    paths:
      - "info.json" # Triggers only if the mod info file is updated
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: get mod_version
        id: mod_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "info.json"
          prop_path: "version"
      - name: get factorio_version
        id: factorio_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "info.json"
          prop_path: "factorio_version"
      - name: get mod name
        id: mod_name
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "info.json"
          prop_path: "name"
      - name: Zip mod
        run: bash ./.scripts/zip_mod.sh
      - name: Upload the mod on mods.factorio.com
        env:
          FACTORIO_MOD_API_KEY: ${{ secrets.FACTORIO_MOD_API_KEY }}
        run: bash ./.scripts/upload.sh
